/*
    Comment : Comment are a piece of code that is a for documentation purpose.
                the programming language will just avoid comment during execution.
    There are two ways to create comment 
    Note : In vscode use "CTRL+/" to commenting the selected line or deselecting selected line.
                                1. Single line comment -> pair of forward slash
                                2. Multiline Comment -> /*
                                                        .....
                                                        .....
                                                        .....
                                                        .....
                                                        */
console.log("single line comment"); 
//line


console.log("Multiple comment");
/*
    ....
    ....
    ....
    ....
*/
